### ISSUE TITLE
Fixed order based on slug

### ISSUE THREAD

**Issue by thunder87** [craftcms/element-api#190]
### Description
Unable to order entries based on the order the slugs are received.

### Steps to reproduce

1. Copy below entries.json and view the entries.json output in the browser.
2. Order will be the same regardless of how the slugs are ordered.

### Additional info

```
return [
    'endpoints' => [
        'entries.json' => function() {
            $slugs = Craft::$app->getRequest()->getRequiredQueryParam('slugs');

              return [
                  'elementType' => Entry::class,
                  'criteria' => [
                      'slug' => $slugs
                  ],
                  'transformer' => function (Entry $entry) {
                      return [
                          "title" => $entry->title,
                      ];
                  },
              ];
        }
    ]
]
```

- Craft version: 4.9.0
- PHP version: 8.1.27
- Database driver & version: MySQL 8.0.33
- Plugins & versions: Element-api 4.1.0

**Comment by i-just** [comment]
Hi, thanks for reaching out! This is expected behaviour.

By default, [entries are ordered](https://craftcms.com/docs/4.x/entries.html#orderby) by `postDate DESC, elements.id DESC`. For your entries endpoint, you can provide your own order via `criteria` > `orderBy`. 

There’s also the `fixedOrder` option, which might be helpful if you’re querying by ids: https://craftcms.com/docs/4.x/entries.html#fixedorder.

I hope this helps!
