### ISSUE TITLE
Craft CLI exception when element api is configured

### ISSUE THREAD

**Issue by thaoms** [craftcms/element-api#80]
I'm fetching some data before using the element api:

````
'criteria' => [
         'section' => 'productions',
         'limit' => 10,
	'search' => [
		'query' => 'title:' . Craft::$app->getRequest()->getParam('q'),
		'subLeft' => true,
		'subRight' => true
	]
],
````

But when using the Craft cli with `./craft` I get this error:

````
Exception 'yii\base\UnknownMethodException' with message 
'Calling unknown method: craft\console\Request::getParam()'

/vendor/yiisoft/yii2/base/Component.php:300
````

Not really sure where to post this issue.

**Comment by angrybrad** [comment]
Params in a querystring only exist in the context of a web browser/request, not at the console.  If you don't want that code to run in the context of a console request, you can do something like:

    'query' => !Craft::$app->getRequest()->getIsConsoleRequest() ? 'title:' . Craft::$app->getRequest()->getParam('q') : null,

**Comment by brandonkelly** [comment]
Rather than modify your `query` logic, you could leave that as-is, but place all of your endpoint config array inside an anonymous function. (See [Dynamic URL Patterns and Endpoint Configurations](https://github.com/craftcms/element-api#dynamic-url-patterns-and-endpoint-configurations).)

```php
'endpoint-url-pattern' => function() {
    return [
        'criteria' => [
            'section' => 'productions',
            'limit' => 10,
            'search' => [
                'query' => 'title:' . Craft::$app->getRequest()->getParam('q'),
                'subLeft' => true,
                'subRight' => true,
            ],
        ],
        // ...
    ];
},
```

That way, your endpoint config will only be generated when the endpoint is actually requested, rather than on every web & console request.

**Comment by brandonkelly** [comment]
@carlcs Yeah good idea, now all endpoint config examples use a function.
